Search.appendIndex(
    [
                {
            "fqsen": "\\Ren\\Tanto\\API\\VKApiAnswer",
            "name": "VKApiAnswer",
            "summary": "Vkontakte\u0020\u0028vk.com\u0029\u0020API\u0020answer",
            "url": "classes/Ren-Tanto-API-VKApiAnswer.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VKApiAnswer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020this\u0020answer\u0020with\u0020raw\u0020API\u0020response",
            "url": "classes/Ren-Tanto-API-VKApiAnswer.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VKApiAnswer\u003A\u003Ais_ok\u0028\u0029",
            "name": "is_ok",
            "summary": "Returns\u0020if\u0020API\u0020request\u0020wasn\u0027t\u0020failed",
            "url": "classes/Ren-Tanto-API-VKApiAnswer.html#method_is_ok"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VKApiAnswer\u003A\u003A\u0024status",
            "name": "status",
            "summary": "If\u0020API\u0020request\u0020failed\u0020with\u0020error",
            "url": "classes/Ren-Tanto-API-VKApiAnswer.html#property_status"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VKApiAnswer\u003A\u003A\u0024response",
            "name": "response",
            "summary": "API\u0020response\u0020as\u0020JSON\u0020array\nhttps\u003A\/\/dev.vk.com\/reference\/json\u002Dschema",
            "url": "classes/Ren-Tanto-API-VKApiAnswer.html#property_response"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkApiClient",
            "name": "VkApiClient",
            "summary": "Vkontakte\u0020\u0028vk.com\u0029\u0020API\u0020client",
            "url": "classes/Ren-Tanto-API-VkApiClient.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkApiClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020client\u0020with\u0020the\u0020given\u0020token",
            "url": "classes/Ren-Tanto-API-VkApiClient.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkApiClient\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "",
            "url": "classes/Ren-Tanto-API-VkApiClient.html#method_request"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkApiClient\u003A\u003A\u0024token",
            "name": "token",
            "summary": "Access\u0020token\nhttps\u003A\/\/dev.vk.com\/api\/access\u002Dtoken\/getting\u002Dstarted",
            "url": "classes/Ren-Tanto-API-VkApiClient.html#property_token"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkLongPollClient",
            "name": "VkLongPollClient",
            "summary": "Vkontakte\u0020\u0028vk.com\u0029\u0020longpoll\u0020client",
            "url": "classes/Ren-Tanto-API-VkLongPollClient.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkLongPollClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020client\u0020with\u0020the\u0020given\u0020server\u0020address,\u0020secret\u0020key\u0020and\u0020ts\nhttps\u003A\/\/dev.vk.com\/api\/bots\u002Dlong\u002Dpoll\/getting\u002Dstarted",
            "url": "classes/Ren-Tanto-API-VkLongPollClient.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkLongPollClient\u003A\u003Apoll\u0028\u0029",
            "name": "poll",
            "summary": "Polls\u0020events\u0020from\u0020long\u0020poll\u0020server\nhttps\u003A\/\/dev.vk.com\/api\/community\u002Devents\/json\u002Dschema",
            "url": "classes/Ren-Tanto-API-VkLongPollClient.html#method_poll"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkLongPollClient\u003A\u003A\u0024server",
            "name": "server",
            "summary": "Longpoll\u0020server\u0020URL",
            "url": "classes/Ren-Tanto-API-VkLongPollClient.html#property_server"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkLongPollClient\u003A\u003A\u0024key",
            "name": "key",
            "summary": "Secret\u0020session\u0020key",
            "url": "classes/Ren-Tanto-API-VkLongPollClient.html#property_key"
        },                {
            "fqsen": "\\Ren\\Tanto\\API\\VkLongPollClient\u003A\u003A\u0024ts",
            "name": "ts",
            "summary": "Last\u0020event\u0020number",
            "url": "classes/Ren-Tanto-API-VkLongPollClient.html#property_ts"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend",
            "name": "Backend",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_get_name"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aon_start\u0028\u0029",
            "name": "on_start",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_on_start"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aon_shutdown\u0028\u0029",
            "name": "on_shutdown",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_on_shutdown"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_loop"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\VkMessageContext",
            "name": "VkMessageContext",
            "summary": "Vkontakte\u0020\u0028vk.com\u0029\u0020message\u0020context",
            "url": "classes/Ren-Tanto-Backend-VkMessageContext.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\VkMessageContext\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020context\u0020with\u0020API\u0020client\u0020handle\u0020and\u0020raw\u0020API\u0020response",
            "url": "classes/Ren-Tanto-Backend-VkMessageContext.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\VkMessageContext\u003A\u003Areply\u0028\u0029",
            "name": "reply",
            "summary": "Sends\u0020message\u0020in\u0020chat\u0020what\u0020message\u0020belong",
            "url": "classes/Ren-Tanto-Backend-VkMessageContext.html#method_reply"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\VkMessageContext\u003A\u003A\u0024api",
            "name": "api",
            "summary": "API\u0020client\u0020handle",
            "url": "classes/Ren-Tanto-Backend-VkMessageContext.html#property_api"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\VkMessageContext\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend-VkMessageContext.html#property_object"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\VkMessageContext\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend-VkMessageContext.html#property_message"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte",
            "name": "Vkontakte",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initializes\u0020context\u0020with\u0020access\u0020token\nhttps\u003A\/\/dev.vk.com\/api\/access\u002Dtoken\/getting\u002Dstarted",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Backend\u0020destructor",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method___destruct"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "Backend\u0020name\u0020getter",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method_get_name"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Prints\u0020message\u0020in\u0020console\u0020with\u0020backend\u0020name",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method_log"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003Aon_start\u0028\u0029",
            "name": "on_start",
            "summary": "Function\u0020called\u0020on\u0020backend\u0020start\nTests\u0020provided\u0020token\u0020and\u0020retrieves\u0020longpoll\u0020server",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method_on_start"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003Aon_shutdown\u0028\u0029",
            "name": "on_shutdown",
            "summary": "Function\u0020called\u0020on\u0020backend\u0020shutdown\u0020\u0028error\u0029",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method_on_shutdown"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "Backend\u0020loop\nPolls\u0020events\u0020from\u0020longpoll\u0020server\u0020and\u0020handles\u0020it",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#method_loop"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A\u0024token",
            "name": "token",
            "summary": "Access\u0020token\nhttps\u003A\/\/dev.vk.com\/api\/access\u002Dtoken\/getting\u002Dstarted",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#property_token"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A\u0024api",
            "name": "api",
            "summary": "API\u0020client\u0020handle",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#property_api"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A\u0024lp_client",
            "name": "lp_client",
            "summary": "Longpoll\u0020client\u0020handle",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#property_lp_client"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "Array\u0020of\u0020handlers",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#property_handlers"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Name\u0020of\u0020backend\u0020that\u0020used\u0020in\u0020logging",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#property_name"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\\Vkontakte\u003A\u003A\u0024next_request",
            "name": "next_request",
            "summary": "Timestamp\u0020when\u0020next\u0020poll\u0020request\u0020should\u0020be\u0020done",
            "url": "classes/Ren-Tanto-Backend-Vkontakte.html#property_next_request"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto",
            "name": "Tanto",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Aadd_backend\u0028\u0029",
            "name": "add_backend",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_add_backend"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Aon_message\u0028\u0029",
            "name": "on_message",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_on_message"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_start"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Astop\u0028\u0029",
            "name": "stop",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_stop"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003A\u0024backends",
            "name": "backends",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#property_backends"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#property_handlers"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\API",
            "name": "API",
            "summary": "",
            "url": "namespaces/ren-tanto-api.html"
        },                {
            "fqsen": "\\Ren\\Tanto",
            "name": "Tanto",
            "summary": "",
            "url": "namespaces/ren-tanto.html"
        },                {
            "fqsen": "\\Ren",
            "name": "Ren",
            "summary": "",
            "url": "namespaces/ren.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend",
            "name": "Backend",
            "summary": "",
            "url": "namespaces/ren-tanto-backend.html"
        }            ]
);
