Search.appendIndex(
    [
                {
            "fqsen": "\\Ren\\Tanto\\Backend",
            "name": "Backend",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_get_name"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aon_start\u0028\u0029",
            "name": "on_start",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_on_start"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aon_shutdown\u0028\u0029",
            "name": "on_shutdown",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_on_shutdown"
        },                {
            "fqsen": "\\Ren\\Tanto\\Backend\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "",
            "url": "classes/Ren-Tanto-Backend.html#method_loop"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto",
            "name": "Tanto",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Aadd_backend\u0028\u0029",
            "name": "add_backend",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_add_backend"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Aon_message\u0028\u0029",
            "name": "on_message",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_on_message"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_start"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003Astop\u0028\u0029",
            "name": "stop",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#method_stop"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003A\u0024backends",
            "name": "backends",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#property_backends"
        },                {
            "fqsen": "\\Ren\\Tanto\\Tanto\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "",
            "url": "classes/Ren-Tanto-Tanto.html#property_handlers"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiAnswer",
            "name": "VKApiAnswer",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiAnswer.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiAnswer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiAnswer.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiAnswer\u003A\u003Ais_ok\u0028\u0029",
            "name": "is_ok",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiAnswer.html#method_is_ok"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiAnswer\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiAnswer.html#property_status"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiAnswer\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiAnswer.html#property_response"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiClient",
            "name": "VKApiClient",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiClient.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiClient.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiClient\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiClient.html#method_request"
        },                {
            "fqsen": "\\Ren\\Tanto\\VKApiClient\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/Ren-Tanto-VKApiClient.html#property_token"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkLongPollClient",
            "name": "VkLongPollClient",
            "summary": "",
            "url": "classes/Ren-Tanto-VkLongPollClient.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkLongPollClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Ren-Tanto-VkLongPollClient.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkLongPollClient\u003A\u003Apoll\u0028\u0029",
            "name": "poll",
            "summary": "",
            "url": "classes/Ren-Tanto-VkLongPollClient.html#method_poll"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkLongPollClient\u003A\u003A\u0024server",
            "name": "server",
            "summary": "",
            "url": "classes/Ren-Tanto-VkLongPollClient.html#property_server"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkLongPollClient\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/Ren-Tanto-VkLongPollClient.html#property_key"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkLongPollClient\u003A\u003A\u0024ts",
            "name": "ts",
            "summary": "",
            "url": "classes/Ren-Tanto-VkLongPollClient.html#property_ts"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkMessageContext",
            "name": "VkMessageContext",
            "summary": "",
            "url": "classes/Ren-Tanto-VkMessageContext.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkMessageContext\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Ren-Tanto-VkMessageContext.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkMessageContext\u003A\u003Areply\u0028\u0029",
            "name": "reply",
            "summary": "",
            "url": "classes/Ren-Tanto-VkMessageContext.html#method_reply"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkMessageContext\u003A\u003A\u0024api",
            "name": "api",
            "summary": "",
            "url": "classes/Ren-Tanto-VkMessageContext.html#property_api"
        },                {
            "fqsen": "\\Ren\\Tanto\\VkMessageContext\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/Ren-Tanto-VkMessageContext.html#property_object"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte",
            "name": "Vkontakte",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method___construct"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method___destruct"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method_get_name"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method_log"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003Aon_start\u0028\u0029",
            "name": "on_start",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method_on_start"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003Aon_shutdown\u0028\u0029",
            "name": "on_shutdown",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method_on_shutdown"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#method_loop"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#property_token"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A\u0024api",
            "name": "api",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#property_api"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A\u0024lp_client",
            "name": "lp_client",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#property_lp_client"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A\u0024handlers",
            "name": "handlers",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#property_handlers"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#property_name"
        },                {
            "fqsen": "\\Ren\\Tanto\\Vkontakte\u003A\u003A\u0024next_request",
            "name": "next_request",
            "summary": "",
            "url": "classes/Ren-Tanto-Vkontakte.html#property_next_request"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Ren\\Tanto",
            "name": "Tanto",
            "summary": "",
            "url": "namespaces/ren-tanto.html"
        },                {
            "fqsen": "\\Ren",
            "name": "Ren",
            "summary": "",
            "url": "namespaces/ren.html"
        }            ]
);
